export const actionContants = {
    UPDATE_ALL_LOCATIONS: "UPDATE_ALL_LOCATIONS",
    UPDATE_REVIEW_RECOMMENDATION: "UPDATE_REVIEW_RECOMMENDATION",
    UPDATE_LOCATION_RECOMMENDATION: "UPDATE_LOCATION_RECOMMENDATION",
}